---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: index.njk
  label: Home
- type: document
  path: about/index.md
  label: About
- type: heading
  label: Content
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
upload_dir: media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run dev --port 8080
