backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "media"
collections:
  - name: "post"
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "posts"}
      - {label: "Body", name: "body", widget: "markdown"}