backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: media
site_url: https://zijspoor.jntn.dev
locale: nl
collections:
  - name: pages
    label: Pages
    files:
      - name: about
        label: About
        file: about/index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
  - name: post
    label: Post
    folder: posts
    create: true
    slug: "{{title}}"
    preview_path: posts/{{title}}
    fields:
      - label: Title
        name: title
        widget: string
      - label: Layout
        name: layout
        widget: hidden
        default: post.njk
      - label: Tags
        name: tags
        widget: hidden
        default: posts
      - label: Body
        name: body
        widget: markdown